import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export const VI = 'vi';
export const EN = 'en';

// Key UI strings — expand as needed
export const STRINGS = {
  vi: {
    home:        'Trang chủ',
    collections: 'Bộ sưu tập',
    kits:        'Áo đấu',
    boots:       'Giày',
    apparel:     'Trang phục',
    newArrivals: 'Sản phẩm mới',
    accessories: 'Phụ kiện',
    flashSale:   'Flash Sale',
    search:      'Tìm kiếm sản phẩm...',
    cart:        'Giỏ hàng',
    wishlist:    'Yêu thích',
    login:       'Đăng nhập',
    register:    'Đăng ký',
    profile:     'Hồ sơ',
    orders:      'Đơn hàng',
    shopNow:     'Mua ngay',
    viewAll:     'Xem tất cả',
    addToCart:   'Thêm vào giỏ',
    buyNow:      'Mua ngay',
    allProducts: 'Tất cả sản phẩm',
    // Extended strings
    products:         'Sản phẩm',
    filterBy:         'Lọc theo',
    sortBy:           'Sắp xếp',
    newest:           'Mới nhất',
    priceAsc:         'Giá tăng dần',
    priceDesc:        'Giá giảm dần',
    topRated:         'Đánh giá cao',
    clearAll:         'Xóa tất cả',
    noProducts:       'Không tìm thấy sản phẩm',
    outOfStock:       'Hết hàng',
    inStock:          'Còn hàng',
    size:             'Kích cỡ',
    color:            'Màu sắc',
    quantity:         'Số lượng',
    reviews:          'Đánh giá',
    writeReview:      'Viết đánh giá',
    loginToReview:    'Đăng nhập để đánh giá',
    submit:           'Gửi',
    cancel:           'Hủy',
    save:             'Lưu',
    delete:           'Xóa',
    edit:             'Chỉnh sửa',
    confirm:          'Xác nhận',
    back:             'Quay lại',
    next:             'Tiếp theo',
    loading:          'Đang tải...',
    error:            'Lỗi',
    success:          'Thành công',
    cartEmpty:        'Giỏ hàng trống',
    checkout:         'Thanh toán',
    total:            'Tổng cộng',
    subtotal:         'Tạm tính',
    shipping:         'Phí vận chuyển',
    free:             'Miễn phí',
    address:          'Địa chỉ',
    phone:            'Số điện thoại',
    name:             'Họ tên',
    email:            'Email',
    password:         'Mật khẩu',
    confirmPassword:  'Xác nhận mật khẩu',
    forgotPassword:   'Quên mật khẩu?',
    rememberMe:       'Ghi nhớ đăng nhập',
    noAccount:        'Chưa có tài khoản?',
    hasAccount:       'Đã có tài khoản?',
    signIn:           'Đăng nhập',
    signUp:           'Đăng ký',
    signOut:          'Đăng xuất',
    myOrders:         'Đơn hàng của tôi',
    myProfile:        'Hồ sơ cá nhân',
    newArrivalsTitle: 'Sản phẩm mới nhất',
    flashSaleTitle:   'Flash Sale',
    // Section titles — CategoriesShowcase & ShopByClub
    categoryBadge:        'Danh Mục',
    exploreCategoryTitle: 'KHÁM PHÁ DANH MỤC',
    exploreCategoryTagline: 'Tất cả sản phẩm — Một nơi duy nhất',
    exploreCategoryDesc:  'Tìm kiếm theo danh mục yêu thích của bạn',
    byCategory:           'Theo Danh Mục',
    bestSellers:          'BÁN CHẠY NHẤT',
    featuredBadge:        '★ Nổi bật',
    noProductsInCategory: 'Chưa có sản phẩm trong danh mục này',
    viewAllProducts:      'Xem tất cả sản phẩm',
    clubBadge:            'Câu Lạc Bộ',
    shopByClubTitle:      'MUA THEO CLB',
    shopByClubTagline:    'Trang bị đúng màu áo — Đúng đội bóng của bạn',
    shopByClubDesc:       'Áo đấu từ các CLB hàng đầu thế giới & đội tuyển quốc gia',
    tradeIn:          'Thu cũ đổi mới',
    news:             'Tin tức',
    contactUs:        'Liên hệ',
    newsletter:       'Đăng ký nhận tin',
    newsletterDesc:   'Nhận ưu đãi độc quyền và tin tức mới nhất',
    subscribe:        'Đăng ký',
    yourEmail:        'Email của bạn',
    heroSubtitle:     'Nơi bắt đầu hành trình chinh phục',
    shopCollection:   'Khám phá bộ sưu tập',
    viewMore:         'Xem thêm',
    category:         'Danh mục',
    brand:            'Thương hiệu',
    price:            'Giá',
    sale:             'Khuyến mãi',
    // Hero section
    heroEyebrow:      'Bước chân đầu tiên của giấc mơ',
    heroBig1:         'BẮT ĐẦU',
    heroBig2:         'TỪ ĐÂY',
    heroTagline1:     'Trang bị đẳng cấp — Thi đấu đỉnh cao',
    heroTagline2:     'Giày, áo đấu & phụ kiện bóng đá cao cấp nhất 2026',
    heroCTA1:         'MUA NGAY',
    heroCTA2:         'Xem bộ sưu tập',
    heroStat1:        'Sản phẩm',
    heroStat2:        'Khách hàng',
    heroStat3:        'Đánh giá',
    heroScroll:       'Cuộn để khám phá',
    heroDrag:         'Giữ & kéo để xoay',
    // Navbar
    freeShipping:     'Miễn phí vận chuyển cho đơn hàng trên',
    shopNowLink:      'Mua ngay',
    recentSearches:   'Tìm kiếm gần đây',
    trending:         'Xu hướng',
    viewAllResults:   'Xem tất cả kết quả cho',
    account:          'Tài khoản',
    myProfile:        'Hồ sơ của tôi',
    adminPanel:       'Bảng quản trị',
    searchPlaceholder:'Tìm sản phẩm, thương hiệu...',
    // Cart
    freeShippingMsg:   'Bạn được miễn phí vận chuyển!',
    addMoreForFreeShip:'Mua thêm {amount} để được miễn ship',
    orderSummary:      'Tóm tắt đơn hàng',
    promoCode:         'Mã giảm giá',
    apply:             'Áp dụng',
    continueShopping:  'Tiếp tục mua sắm',
    emptyCartMsg:      'Chưa có sản phẩm nào trong giỏ',
    emptyCartSub:      'Khám phá bộ sưu tập của chúng tôi',
    // Checkout
    shippingInfo:      'Thông tin giao hàng',
    fullName:          'Họ và tên',
    streetAddress:     'Địa chỉ',
    city:              'Thành phố',
    paymentMethod:     'Phương thức thanh toán',
    placeOrder:        'Đặt hàng',
    processing:        'Đang xử lý...',
    cod:               'Thanh toán khi nhận hàng',
    bankTransfer:      'Chuyển khoản ngân hàng',
    orderTotal:        'Tổng đơn hàng',
    // ProductDetail
    selectSize:        'Chọn size',
    selectColor:       'Chọn màu',
    addingToCart:      'Đang thêm...',
    outOfStockMsg:     'Hết hàng',
    description:       'Mô tả sản phẩm',
    relatedProducts:   'Sản phẩm liên quan',
    customerReviews:   'Đánh giá khách hàng',
    noReviews:         'Chưa có đánh giá',
    yourReview:        'Đánh giá của bạn',
    rating:            'Đánh giá',
    shareProduct:      'Chia sẻ',
    addedToWishlist:   'Đã thêm vào yêu thích',
    removeFromWishlist:'Xóa khỏi yêu thích',
    sizeGuide:         'Hướng dẫn chọn size',
    instock:           'Còn hàng',
    // Login / Register
    welcomeBack:       'Chào mừng trở lại',
    loginSubtitle:     'Đăng nhập để tiếp tục hành trình',
    orContinueWith:    'Hoặc tiếp tục với',
    createAccount:     'Tạo tài khoản',
    registerSubtitle:  'Tham gia cộng đồng MiQ Sport',
    fullNameLabel:     'Họ và tên',
    agreeTerms:        'Tôi đồng ý với điều khoản dịch vụ',
    passwordStrength:  'Độ mạnh mật khẩu',
    weak:              'Yếu',
    medium:            'Trung bình',
    strong:            'Mạnh',
    // General / Footer
    featuredCategories:'Danh mục nổi bật',
    exploreAll:        'Khám phá tất cả',
    tradeInTitle:      'Thu cũ đổi mới',
    tradeInSub:        'Đổi giày cũ lấy giày mới với ưu đãi hấp dẫn',
    getEstimate:       'Nhận báo giá',
    footerTagline:     'Nơi bắt đầu mọi hành trình',
    quickLinks:        'Liên kết nhanh',
    followUs:          'Theo dõi chúng tôi',
    hotline:           'Hotline',
    workingHours:      'Giờ làm việc',
    allRightsReserved: 'Đã đăng ký bản quyền',
    privacyPolicy:     'Chính sách bảo mật',
    terms:             'Điều khoản sử dụng',
    // Order statuses
    orderStatusPending:    'Chờ xác nhận',
    orderStatusConfirmed:  'Đã xác nhận',
    orderStatusShipping:   'Đang giao',
    orderStatusDelivered:  'Đã giao',
    orderStatusCancelled:  'Đã hủy',
    orderStatusProcessing: 'Đang xử lý',
    // Toast messages
    addedToCart:           'Đã thêm vào giỏ hàng!',
    pleaseSelectSize:      'Vui lòng chọn size',
    outOfStockToast:       'Tạm hết hàng',
    removedFromWishlist:   'Đã bỏ khỏi yêu thích',
    orderUpdated:          'Trạng thái đơn hàng vừa được cập nhật!',
    reviewTooShort:        'Bình luận cần ít nhất 10 ký tự',
    reviewDeleted:         'Đã xóa đánh giá',
    addedToWishlist:       'Đã thêm vào yêu thích!',
    outOfStockWishlist:    'Sản phẩm đã hết hàng',
    avatarUpdated:         'Cập nhật ảnh đại diện thành công',
    profileUpdated:        'Cập nhật thành công',
    nameRequired:          'Tên không được để trống',
    passwordMismatch:      'Mật khẩu mới không khớp',
    passwordTooShort:      'Mật khẩu mới phải có ít nhất 8 ký tự',
    passwordChanged:       'Đổi mật khẩu thành công',
    addressDeleted:        'Đã xóa địa chỉ',
    addressAdded:          'Thêm địa chỉ thành công',
    defaultSet:            'Đã đặt địa chỉ mặc định',
    // Profile page
    personalInfo:          'Thông tin cá nhân',
    myAddresses:           'Địa chỉ giao hàng',
    changePassword:        'Đổi mật khẩu',
    saveChanges:           'Lưu thay đổi',
    addAddress:            'Thêm địa chỉ',
    editAddress:           'Sửa địa chỉ',
    addNewAddress:         'Thêm địa chỉ mới',
    defaultBadge:          'Mặc định',
    setDefault:            'Đặt làm mặc định',
    noOrders:              'Chưa có đơn hàng nào',
    noAddresses:           'Chưa có địa chỉ nào',
    addAddressHint:        'Thêm địa chỉ để thanh toán nhanh hơn',
    totalOrdersStat:       'Tổng đơn',
    totalSpent:            'Đã chi',
    lastOrderStat:         'Đơn cuối',
    deliverTo:             'Giao đến',
    avatarHint:            'JPG, PNG — tối đa 5MB. Ảnh sẽ được crop 200×200px.',
    currentPassword:       'Mật khẩu hiện tại',
    newPassword:           'Mật khẩu mới',
    confirmNewPassword:    'Xác nhận mật khẩu mới',
    addressLabel:          'Nhãn',
    addressLabelPlaceholder: 'VD: Nhà, Công ty...',
    recipientName:         'Họ tên người nhận',
    province:              'Tỉnh / Thành phố',
    district:              'Quận / Huyện',
    ward:                  'Phường / Xã',
    streetDetail:          'Số nhà, tên đường',
    setAsDefault:          'Đặt làm địa chỉ mặc định',
    wishlistComingSoon:    'Sắp ra mắt',
    wishlistDevMsg:        'Tính năng Wishlist đang được phát triển...',
    tabAll:                'Tất cả',
    filterLabel:           'Lọc',
    // Order detail / success
    orderNotFound:         'Không tìm thấy đơn hàng',
    backToProfile:         '← Về trang cá nhân',
    orderCode:             'Mã đơn hàng',
    orderCancelledMsg:     'Đơn hàng đã bị huỷ',
    orderSuccess:          'ĐẶT HÀNG THÀNH CÔNG!',
    orderThankYou:         'Cảm ơn bạn đã mua sắm tại MiQ.',
    orderRef:              'Mã đơn:',
    backHome:              'Về trang chủ',
    continueShopping2:     'Tiếp tục mua sắm',
    // Wishlist page
    wishlistTitle:         'Yêu thích',
    wishlistEmpty:         'Chưa có sản phẩm nào',
    exploreShopping:       'Khám phá sản phẩm',
    // Review
    starTerrible:          'Rất tệ',
    starBad:               'Tệ',
    starOk:                'Bình thường',
    starGood:              'Tốt',
    starExcellent:         'Xuất sắc!',
    // Navbar mega config
    brandCollectionsTitle: 'Bộ sưu tập thương hiệu',
    kitsMenuTitle:         'Áo đấu bóng đá',
    bootsMenuTitle:        'Giày bóng đá',
    clubKits:              'Áo CLB',
    nationalKits:          'Áo đội tuyển',
    trainingKits:          'Bộ tập luyện',
    goalkeeperKits:        'Áo thủ môn',
    naturalGroundFG:       'Sân tự nhiên (FG)',
    softGroundSG:          'Sân mềm (SG)',
    artificialGroundAG:    'Sân nhân tạo (AG)',
    indoorFutsal:          'Sân trong nhà / Futsal',
    exploreNow:            'Khám phá ngay',
    viewAllKits:           'Xem tất cả áo đấu',
    viewAllBoots:          'Xem tất cả giày',
    seasonColl:            'Bộ sưu tập 2024/25',
    eliteSpeed:            'Công nghệ tốc độ Elite',
    miqFlagship:           'BST MiQ Flagship 2025/26',
    // ProductListing sub-categories
    allKitsLabel:          'Tất cả áo đấu',
    allBootsLabel:         'Tất cả giày',
    allApparelLabel:       'Tất cả trang phục',
    allAccessoriesLabel:   'Tất cả phụ kiện',
    kitGroupLabel:         'Áo đấu',
    bootGroupLabel:        'Giày đá bóng',
    apparelGroupLabel:     'Trang phục',
    accessoriesGroupLabel: 'Phụ kiện',
    fgLabel:               'Sân tự nhiên FG',
    sgLabel:               'Sân mềm SG',
    agLabel:               'Sân nhân tạo AG',
    indoorLabel:           'Futsal / Indoor',
    // Price ranges
    under500k:             'Dưới 500K',
    range500to1m:          '500K – 1 triệu',
    range1to2m:            '1 – 2 triệu',
    over2m:                'Trên 2 triệu',
    // Chat widget
    chatSupport:           'Hỗ trợ trực tuyến',
    closeChat:             'Đóng chat',
    openChat:              'Mở chat hỗ trợ',
    chatWelcome:           'Chào bạn! Chúng tôi có thể giúp gì?',
    chatPlaceholder:       'Nhắn tin...',
    chatSend:              'Gửi tin nhắn',
    // Product badges & actions
    newArrivalBadge:       'MỚI RA MẮT',
    newBadge:              'MỚI',
    viewDetail:            'Xem chi tiết',
    // FlashSale
    flashSaleSubtitle:     'Săn hàng giảm giá đỉnh cao — Chỉ trong hôm nay!',
    endsIn:                'Kết thúc sau',
    hours:                 'Giờ',
    minutes:               'Phút',
    seconds:               'Giây',
    viewAllDeals:          'Xem tất cả ưu đãi',
    noFlashSaleProducts:   'Chưa có sản phẩm flash sale',
    almostSoldOut:         '🔥 Sắp hết!',
    // Review section
    reviewsTitle:          'ĐÁNH GIÁ SẢN PHẨM',
    satisfactionLevel:     'Mức độ hài lòng',
    reviewCommentLabel:    'Nhận xét',
    minCharsNote:          'tối thiểu 10 ký tự',
    reviewPlaceholder:     'Chia sẻ trải nghiệm thực tế về chất lượng, size, độ bám sân...',
    charEnough:            '✓ Đủ ký tự',
    updateReviewTitle:     'CẬP NHẬT ĐÁNH GIÁ',
    writeReviewTitle:      'VIẾT ĐÁNH GIÁ',
    editingBadge:          'Đang chỉnh sửa',
    updateReviewBtn:       'Cập nhật đánh giá',
    sendReviewBtn:         'Gửi đánh giá',
    reviewUpdated:         '✏️ Đã cập nhật đánh giá!',
    reviewThanks:          '⭐ Cảm ơn đánh giá của bạn!',
    deleteReviewConfirm:   'Xóa đánh giá này?',
    beFirstReview:         'Hãy là người đầu tiên chia sẻ trải nghiệm!',
    loginToReviewMsg:      'Đăng nhập và mua sản phẩm để để lại đánh giá.',
    buyToReviewMsg:        'Bạn cần mua và nhận sản phẩm này mới có thể đánh giá.',
    checkingEligibility:   'Đang kiểm tra quyền đánh giá...',
    reviewCountSuffix:     'đánh giá',
    // Profile
    loadOrdersError:       'Không tải được đơn hàng',
    addressUpdated:        'Cập nhật địa chỉ thành công',
    deleteAddressConfirm:  'Xóa địa chỉ này?',
    passwordValidLength:   '✓ Độ dài hợp lệ',
    // Cancel order
    cancelOrder:          'Hủy đơn hàng',
    cancelOrderConfirm:   'Bạn có chắc muốn hủy đơn hàng này không?',
    orderCancelled:       'Đã hủy đơn hàng thành công',
    cancelling:           'Đang hủy...',
    // Coupon
    enterCouponCode:      'Nhập mã giảm giá',
    couponApplied:        'Áp dụng mã thành công!',
    couponInvalid:        'Mã giảm giá không hợp lệ hoặc đã hết hạn',
    discount:             'Giảm giá',
    couponPlaceholder:    'VD: SALE10',
    // Jersey print
    jerseyPrintBadge:     'Dịch vụ in ấn',
    jerseyPrintTitle:     'ĐẶT IN ÁO THEO YÊU CẦU',
    jerseyType:           'Loại áo',
    jerseyName:           'Tên in trên áo',
    jerseyNumber:         'Số áo',
    jerseyFont:           'Kiểu chữ',
    jerseyQuantity:       'Số lượng',
    jerseyColor:          'Màu áo',
    jerseyLogoUrl:        'Link logo đội (nếu có)',
    jerseyNotes:          'Ghi chú thêm',
    jerseySubmit:         'Gửi đơn đặt hàng',
    jerseySuccess:        'Đơn in áo đã được gửi! Chúng tôi sẽ liên hệ trong 24h.',
    jerseyContactPhone:   'Số điện thoại liên hệ',
    jerseyDeliveryAddr:   'Địa chỉ giao hàng',
    jerseyDesignClub:     'Theo CLB',
    jerseyDesignNational: 'Đội tuyển',
    jerseyDesignCustom:   'Thiết kế tự do',
    // Size recommendation
    sizeChartTitle:       'Bảng Size',
    myHeight:             'Chiều cao (cm)',
    myWeight:             'Cân nặng (kg)',
    recommendedSize:      'Size gợi ý',
    checkMySize:          'Kiểm tra size',
    // Product comparison
    compareTitle:         'SO SÁNH SẢN PHẨM',
    compareEmpty:         'Chưa có sản phẩm để so sánh',
    addToCompare:         'Thêm vào so sánh',
    removeFromCompare:    'Xóa khỏi so sánh',
    compare:              'So sánh',
    clearCompare:         'Xóa danh sách so sánh',
    compareHint:          'Chọn tối đa 2 sản phẩm để so sánh',
    compareNow:           'So sánh ngay',
    compareRemove:        'Xóa',
    // Store locations
    storeTitle:           'CỬA HÀNG',
    storeLocationsBadge:  'Hệ Thống Cửa Hàng',
    storeLocationsDesc:   'Ghé thăm và trải nghiệm sản phẩm trực tiếp tại các chi nhánh MiQ',
    viewMap:              'Xem bản đồ',
    // News section
    newsTitle:            'TIN TỨC MiQ',
    newsBadge:            'Tin Tức & Cập Nhật',
    newsSubtitle:         'Cập nhật mới nhất từ thế giới bóng đá',
    readMore:             'Đọc tiếp',
    viewAllNews:          'Xem tất cả',
    // Jersey printing features
    jerseyPriceRef:       'Giá tham khảo',
    jerseyOrderBtn:       'Đặt In Ngay',
    jerseyCallBtn:        'Gọi tư vấn',
    jerseyTotalPrinted:   'Tổng đã in',
    jerseyTotalUnits:     '2,400+ áo',
    jerseyFontSelected:   'Font đang chọn',
    jerseyF1Label:        'In tên & số áo',
    jerseyF1Desc:         'Nhiều font chữ chuyên nghiệp',
    jerseyF2Label:        'Chọn màu tự do',
    jerseyF2Desc:         'Hơn 20 màu sắc nổi bật',
    jerseyF3Label:        'Theo đội hoặc cá nhân',
    jerseyF3Desc:         'Từ 1 đến hàng trăm chiếc',
    jerseyF4Label:        'Giao nhanh 3-5 ngày',
    jerseyF4Desc:         'Sau khi xác nhận đơn',
    jerseyPriceFrom:      'từ 120.000đ',
    jerseyPriceUnit:      '/ áo',
    jerseyDiscount:       'Giảm 10% cho đơn từ 10 áo. Liên hệ để nhận báo giá đội bóng.',
    // Photo reviews
    uploadReviewImages:   'Thêm ảnh',
    maxReviewImages:      'Tối đa 3 ảnh',
    reviewImages:         'Ảnh đánh giá',
    // Body measurement size recommendation
    bodyMeasurement:      'Gợi ý size theo số đo',
    heightLabel:          'Chiều cao (cm)',
    weightLabel:          'Cân nặng (kg)',
    checkSize:            'Gợi ý size',
    sizeResult:           'Size phù hợp với bạn',
  },
  en: {
    home:        'Home',
    collections: 'Collections',
    kits:        'Kits',
    boots:       'Boots',
    apparel:     'Apparel',
    newArrivals: 'New Arrivals',
    accessories: 'Accessories',
    flashSale:   'Flash Sale',
    search:      'Search products...',
    cart:        'Cart',
    wishlist:    'Wishlist',
    login:       'Sign in',
    register:    'Sign up',
    profile:     'Profile',
    orders:      'Orders',
    shopNow:     'Shop now',
    viewAll:     'View all',
    addToCart:   'Add to cart',
    buyNow:      'Buy now',
    allProducts: 'All products',
    // Extended strings
    products:         'Products',
    filterBy:         'Filter by',
    sortBy:           'Sort by',
    newest:           'Newest',
    priceAsc:         'Price: Low to High',
    priceDesc:        'Price: High to Low',
    topRated:         'Top Rated',
    clearAll:         'Clear all',
    noProducts:       'No products found',
    outOfStock:       'Out of stock',
    inStock:          'In stock',
    size:             'Size',
    color:            'Color',
    quantity:         'Quantity',
    reviews:          'Reviews',
    writeReview:      'Write a review',
    loginToReview:    'Sign in to review',
    submit:           'Submit',
    cancel:           'Cancel',
    save:             'Save',
    delete:           'Delete',
    edit:             'Edit',
    confirm:          'Confirm',
    back:             'Back',
    next:             'Next',
    loading:          'Loading...',
    error:            'Error',
    success:          'Success',
    cartEmpty:        'Your cart is empty',
    checkout:         'Checkout',
    total:            'Total',
    subtotal:         'Subtotal',
    shipping:         'Shipping',
    free:             'Free',
    address:          'Address',
    phone:            'Phone',
    name:             'Full name',
    email:            'Email',
    password:         'Password',
    confirmPassword:  'Confirm password',
    forgotPassword:   'Forgot password?',
    rememberMe:       'Remember me',
    noAccount:        "Don't have an account?",
    hasAccount:       'Already have an account?',
    signIn:           'Sign in',
    signUp:           'Sign up',
    signOut:          'Sign out',
    myOrders:         'My orders',
    myProfile:        'My profile',
    newArrivalsTitle: 'New Arrivals',
    flashSaleTitle:   'Flash Sale',
    // Section titles — CategoriesShowcase & ShopByClub
    categoryBadge:        'Categories',
    exploreCategoryTitle: 'EXPLORE CATEGORIES',
    exploreCategoryTagline: 'All products — One place',
    exploreCategoryDesc:  'Browse your favorite categories',
    byCategory:           'By Category',
    bestSellers:          'BEST SELLERS',
    featuredBadge:        '★ Featured',
    noProductsInCategory: 'No products in this category',
    viewAllProducts:      'View all products',
    clubBadge:            'Football Clubs',
    shopByClubTitle:      'SHOP BY CLUB',
    shopByClubTagline:    "Gear up in your team's colors",
    shopByClubDesc:       'Jerseys from top clubs worldwide & national teams',
    tradeIn:          'Trade-In',
    news:             'News',
    contactUs:        'Contact us',
    newsletter:       'Newsletter',
    newsletterDesc:   'Get exclusive deals and the latest news',
    subscribe:        'Subscribe',
    yourEmail:        'Your email',
    heroSubtitle:     'Where your journey begins',
    shopCollection:   'Shop the collection',
    viewMore:         'View more',
    category:         'Category',
    brand:            'Brand',
    price:            'Price',
    sale:             'Sale',
    // Hero section
    heroEyebrow:      'The first step of your dream',
    heroBig1:         'START',
    heroBig2:         'HERE',
    heroTagline1:     'Elite gear — Elite performance',
    heroTagline2:     'Premium football boots, kits & accessories 2026',
    heroCTA1:         'SHOP NOW',
    heroCTA2:         'View collection',
    heroStat1:        'Products',
    heroStat2:        'Customers',
    heroStat3:        'Rating',
    heroScroll:       'Scroll to explore',
    heroDrag:         'Hold & drag to rotate',
    // Navbar
    freeShipping:     'Free shipping on orders over',
    shopNowLink:      'Shop now',
    recentSearches:   'Recent searches',
    trending:         'Trending',
    viewAllResults:   'View all results for',
    account:          'Account',
    myProfile:        'My profile',
    adminPanel:       'Admin panel',
    searchPlaceholder:'Search products, brands...',
    // Cart
    freeShippingMsg:   "You've got free shipping!",
    addMoreForFreeShip:'Add {amount} more for free shipping',
    orderSummary:      'Order summary',
    promoCode:         'Promo code',
    apply:             'Apply',
    continueShopping:  'Continue shopping',
    emptyCartMsg:      'Your cart is empty',
    emptyCartSub:      'Explore our collection',
    // Checkout
    shippingInfo:      'Shipping information',
    fullName:          'Full name',
    streetAddress:     'Street address',
    city:              'City',
    paymentMethod:     'Payment method',
    placeOrder:        'Place order',
    processing:        'Processing...',
    cod:               'Cash on delivery',
    bankTransfer:      'Bank transfer',
    orderTotal:        'Order total',
    // ProductDetail
    selectSize:        'Select size',
    selectColor:       'Select color',
    addingToCart:      'Adding...',
    outOfStockMsg:     'Out of stock',
    description:       'Description',
    relatedProducts:   'Related products',
    customerReviews:   'Customer reviews',
    noReviews:         'No reviews yet',
    yourReview:        'Your review',
    rating:            'Rating',
    shareProduct:      'Share',
    addedToWishlist:   'Added to wishlist',
    removeFromWishlist:'Remove from wishlist',
    sizeGuide:         'Size guide',
    instock:           'In stock',
    // Login / Register
    welcomeBack:       'Welcome back',
    loginSubtitle:     'Sign in to continue your journey',
    orContinueWith:    'Or continue with',
    createAccount:     'Create account',
    registerSubtitle:  'Join the MiQ Sport community',
    fullNameLabel:     'Full name',
    agreeTerms:        'I agree to the terms of service',
    passwordStrength:  'Password strength',
    weak:              'Weak',
    medium:            'Medium',
    strong:            'Strong',
    // General / Footer
    featuredCategories:'Featured categories',
    exploreAll:        'Explore all',
    tradeInTitle:      'Trade-In Program',
    tradeInSub:        'Trade your old shoes for new ones with great deals',
    getEstimate:       'Get estimate',
    footerTagline:     'Where every journey begins',
    quickLinks:        'Quick links',
    followUs:          'Follow us',
    hotline:           'Hotline',
    workingHours:      'Working hours',
    allRightsReserved: 'All rights reserved',
    privacyPolicy:     'Privacy policy',
    terms:             'Terms of use',
    // Order statuses
    orderStatusPending:    'Pending',
    orderStatusConfirmed:  'Confirmed',
    orderStatusShipping:   'Shipping',
    orderStatusDelivered:  'Delivered',
    orderStatusCancelled:  'Cancelled',
    orderStatusProcessing: 'Processing',
    // Toast messages
    addedToCart:           'Added to cart!',
    pleaseSelectSize:      'Please select a size',
    outOfStockToast:       'Out of stock',
    removedFromWishlist:   'Removed from wishlist',
    orderUpdated:          'Order status updated!',
    reviewTooShort:        'Review must be at least 10 characters',
    reviewDeleted:         'Review deleted',
    addedToWishlist:       'Added to wishlist!',
    outOfStockWishlist:    'Product is out of stock',
    avatarUpdated:         'Avatar updated successfully',
    profileUpdated:        'Profile updated',
    nameRequired:          'Name is required',
    passwordMismatch:      'Passwords do not match',
    passwordTooShort:      'Password must be at least 8 characters',
    passwordChanged:       'Password changed successfully',
    addressDeleted:        'Address deleted',
    addressAdded:          'Address added',
    defaultSet:            'Default address updated',
    // Profile page
    personalInfo:          'Personal information',
    myAddresses:           'Delivery addresses',
    changePassword:        'Change password',
    saveChanges:           'Save changes',
    addAddress:            'Add address',
    editAddress:           'Edit address',
    addNewAddress:         'Add new address',
    defaultBadge:          'Default',
    setDefault:            'Set as default',
    noOrders:              'No orders yet',
    noAddresses:           'No addresses yet',
    addAddressHint:        'Add an address for faster checkout',
    totalOrdersStat:       'Total orders',
    totalSpent:            'Total spent',
    lastOrderStat:         'Last order',
    deliverTo:             'Deliver to',
    avatarHint:            'JPG, PNG — max 5MB. Image will be cropped to 200×200px.',
    currentPassword:       'Current password',
    newPassword:           'New password',
    confirmNewPassword:    'Confirm new password',
    addressLabel:          'Label',
    addressLabelPlaceholder: 'E.g. Home, Office...',
    recipientName:         'Recipient name',
    province:              'Province / City',
    district:              'District',
    ward:                  'Ward',
    streetDetail:          'Street address',
    setAsDefault:          'Set as default address',
    wishlistComingSoon:    'Coming soon',
    wishlistDevMsg:        'Wishlist feature is coming soon...',
    tabAll:                'All',
    filterLabel:           'Filter',
    // Order detail / success
    orderNotFound:         'Order not found',
    backToProfile:         '← Back to profile',
    orderCode:             'Order #',
    orderCancelledMsg:     'Order has been cancelled',
    orderSuccess:          'ORDER PLACED!',
    orderThankYou:         'Thank you for shopping at MiQ.',
    orderRef:              'Order ref:',
    backHome:              'Go home',
    continueShopping2:     'Continue shopping',
    // Wishlist page
    wishlistTitle:         'Wishlist',
    wishlistEmpty:         'No items yet',
    exploreShopping:       'Explore products',
    // Review
    starTerrible:          'Terrible',
    starBad:               'Bad',
    starOk:                'OK',
    starGood:              'Good',
    starExcellent:         'Excellent!',
    // Navbar mega config
    brandCollectionsTitle: 'Brand collections',
    kitsMenuTitle:         'Football kits',
    bootsMenuTitle:        'Football boots',
    clubKits:              'Club kits',
    nationalKits:          'National team',
    trainingKits:          'Training kits',
    goalkeeperKits:        'Goalkeeper',
    naturalGroundFG:       'Natural ground (FG)',
    softGroundSG:          'Soft ground (SG)',
    artificialGroundAG:    'Artificial ground (AG)',
    indoorFutsal:          'Indoor / Futsal',
    exploreNow:            'Explore now',
    viewAllKits:           'View all kits',
    viewAllBoots:          'View all boots',
    seasonColl:            '2024/25 Collection',
    eliteSpeed:            'Elite Speed Technology',
    miqFlagship:           'MiQ Flagship 2025/26',
    // ProductListing sub-categories
    allKitsLabel:          'All kits',
    allBootsLabel:         'All boots',
    allApparelLabel:       'All apparel',
    allAccessoriesLabel:   'All accessories',
    kitGroupLabel:         'Kits',
    bootGroupLabel:        'Football boots',
    apparelGroupLabel:     'Apparel',
    accessoriesGroupLabel: 'Accessories',
    fgLabel:               'Firm Ground FG',
    sgLabel:               'Soft Ground SG',
    agLabel:               'Artificial Ground AG',
    indoorLabel:           'Futsal / Indoor',
    // Price ranges
    under500k:             'Under 500K',
    range500to1m:          '500K – 1M',
    range1to2m:            '1M – 2M',
    over2m:                'Over 2M',
    // Chat widget
    chatSupport:           'Live support',
    closeChat:             'Close chat',
    openChat:              'Open support chat',
    chatWelcome:           'Hello! How can we help you?',
    chatPlaceholder:       'Type a message...',
    chatSend:              'Send message',
    // Product badges & actions
    newArrivalBadge:       'NEW ARRIVAL',
    newBadge:              'NEW',
    viewDetail:            'View details',
    // FlashSale
    flashSaleSubtitle:     'Grab top deals — Today only!',
    endsIn:                'Ends in',
    hours:                 'Hrs',
    minutes:               'Min',
    seconds:               'Sec',
    viewAllDeals:          'View all deals',
    noFlashSaleProducts:   'No flash sale products',
    almostSoldOut:         '🔥 Almost out!',
    // Review section
    reviewsTitle:          'PRODUCT REVIEWS',
    satisfactionLevel:     'Rating',
    reviewCommentLabel:    'Comment',
    minCharsNote:          'minimum 10 characters',
    reviewPlaceholder:     'Share your experience about quality, sizing, traction...',
    charEnough:            '✓ Enough characters',
    updateReviewTitle:     'UPDATE REVIEW',
    writeReviewTitle:      'WRITE A REVIEW',
    editingBadge:          'Editing',
    updateReviewBtn:       'Update review',
    sendReviewBtn:         'Submit review',
    reviewUpdated:         '✏️ Review updated!',
    reviewThanks:          '⭐ Thanks for your review!',
    deleteReviewConfirm:   'Delete this review?',
    beFirstReview:         'Be the first to share your experience!',
    loginToReviewMsg:      'Sign in and purchase this product to leave a review.',
    buyToReviewMsg:        'You need to purchase and receive this product to review it.',
    checkingEligibility:   'Checking review eligibility...',
    reviewCountSuffix:     'reviews',
    // Profile
    loadOrdersError:       'Could not load orders',
    addressUpdated:        'Address updated',
    deleteAddressConfirm:  'Delete this address?',
    passwordValidLength:   '✓ Valid length',
    // Cancel order
    cancelOrder:          'Cancel order',
    cancelOrderConfirm:   'Are you sure you want to cancel this order?',
    orderCancelled:       'Order cancelled successfully',
    cancelling:           'Cancelling...',
    // Coupon
    enterCouponCode:      'Enter coupon code',
    couponApplied:        'Coupon applied!',
    couponInvalid:        'Invalid or expired coupon',
    discount:             'Discount',
    couponPlaceholder:    'e.g. SALE10',
    // Jersey print
    jerseyPrintBadge:     'Printing service',
    jerseyPrintTitle:     'CUSTOM JERSEY ORDER',
    jerseyType:           'Jersey type',
    jerseyName:           'Name to print',
    jerseyNumber:         'Jersey number',
    jerseyFont:           'Font style',
    jerseyQuantity:       'Quantity',
    jerseyColor:          'Jersey color',
    jerseyLogoUrl:        'Team logo link (optional)',
    jerseyNotes:          'Additional notes',
    jerseySubmit:         'Submit order',
    jerseySuccess:        'Order submitted! We will contact you within 24h.',
    jerseyContactPhone:   'Contact phone',
    jerseyDeliveryAddr:   'Delivery address',
    jerseyDesignClub:     'Club style',
    jerseyDesignNational: 'National team',
    jerseyDesignCustom:   'Custom design',
    // Size recommendation
    sizeChartTitle:       'Size Chart',
    myHeight:             'Height (cm)',
    myWeight:             'Weight (kg)',
    recommendedSize:      'Recommended size',
    checkMySize:          'Check my size',
    // Product comparison
    compareTitle:         'PRODUCT COMPARISON',
    compareEmpty:         'No products to compare',
    addToCompare:         'Add to compare',
    removeFromCompare:    'Remove from compare',
    compare:              'Compare',
    clearCompare:         'Clear comparison list',
    compareHint:          'Select up to 2 products to compare',
    compareNow:           'Compare now',
    compareRemove:        'Remove',
    // Store locations
    storeTitle:           'STORES',
    storeLocationsBadge:  'Store Network',
    storeLocationsDesc:   'Visit and experience our products in person at MiQ branches',
    viewMap:              'View map',
    // News section
    newsTitle:            'MiQ NEWS',
    newsBadge:            'News & Updates',
    newsSubtitle:         'Latest updates from the football world',
    readMore:             'Read more',
    viewAllNews:          'View all',
    // Jersey printing features
    jerseyPriceRef:       'Reference price',
    jerseyOrderBtn:       'Order Now',
    jerseyCallBtn:        'Call us',
    jerseyTotalPrinted:   'Total printed',
    jerseyTotalUnits:     '2,400+ jerseys',
    jerseyFontSelected:   'Selected font',
    jerseyF1Label:        'Name & number printing',
    jerseyF1Desc:         'Multiple professional fonts',
    jerseyF2Label:        'Free color choice',
    jerseyF2Desc:         'Over 20 vibrant colors',
    jerseyF3Label:        'Team or individual',
    jerseyF3Desc:         'From 1 to hundreds of jerseys',
    jerseyF4Label:        'Fast delivery 3-5 days',
    jerseyF4Desc:         'After order confirmation',
    jerseyPriceFrom:      'from 120,000đ',
    jerseyPriceUnit:      '/ jersey',
    jerseyDiscount:       '10% off for orders of 10+. Contact us for team quotes.',
    // Photo reviews
    uploadReviewImages:   'Add photos',
    maxReviewImages:      'Max 3 photos',
    reviewImages:         'Review photos',
    // Body measurement size recommendation
    bodyMeasurement:      'Size recommendation by body measurements',
    heightLabel:          'Height (cm)',
    weightLabel:          'Weight (kg)',
    checkSize:            'Suggest size',
    sizeResult:           'Recommended size for you',
  },
};

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      lang: VI,
      toggle: () => set((s) => ({ lang: s.lang === VI ? EN : VI })),
      setLang: (v) => set({ lang: v }),
      t: (key) => STRINGS[get().lang]?.[key] ?? key,
    }),
    { name: 'miq-lang' }
  )
);
